#+TITLE: emacs-tips
#+AUTHOR: DarkSun
#+CATEGORY: emacs
#+DATE: [2015-08-04 周二 14:28]
#+OPTIONS: ^:{}

* 保存文件时查看被修改的内容
当使用`C-x s'保存多个文件时,若Emacs提示你是否保存某个文件,可以按`d'键查看buffer与磁盘文件内存之间的差别.

* 如何使windows下的Emacs支持TLS
去[[http://sourceforge.net/projects/ezwinports/files/][ezwinports]] 下载gnutls库,并释放到emacs安装目录下,重启Emacs即可.

重启Emacs后执行 =M-: (gnutls-available-p)= ,结果应该为t,表示Emacs已经支持TLS了.

* evil
** evil-normal-state下,可以通过`-'或`|'快速分割窗口

* ido
** 如何在不使用第三方插件的情况下,将ido的排列方式改为一行一列候选项目
默认情况下,ido将多个候选项排在一排显示,可以通过设置变量`ido-decorations'的第三个元素值或`ido-separator'为'\n'的方式,将ido的排列方式模拟成一行一列候选项的形式.
* org
** 在org中快速跳转
org-mode提供了`org-goto'命令,可以快速定位
#+BEGIN_SRC emacs-lisp
  (define-key org-mode-map (kbd "s-u") #'org-goto)
  (define-key org-mode-map (kbd "s-U") #'org-mark-ring-goto)
#+END_SRC

** 如何在org-table中插入`|'

用 =\vert{}= (不带等号)代替 `|'

** 如何在导出时,保持下划线不转义
可以在一个org的开头,使用下面的设置来关闭下划线转义功能
#+BEGIN_SRC org
  ,#+OPTIONS: ^:nil
#+END_SRC

如果需要更方便的设置,可以设置为
#+BEGIN_SRC org
  ,#+OPTIONS: ^:{}
#+END_SRC
这样当写`a_{b}'时,{}中的b会被转义
而直接写`a_b'则不会转义

* ispell
** 如何让ispell跳过某段文本不做拼写检查
默认情况下,ispell会检查整篇文本中的拼写是否正确. 但通过设置变量`ispell-skip-region-alist'的值,可以指定跳过某几段文本不做拼写检查.

`ispell-skip-region-alist'中的元素格式可以是以下几种:

+ (REGEXP)

  表示跳过匹配REGEXP的文本,不做拼写检查

+ (START-REGEXP . END-REGEXP)
  
  表示从匹配START-REGEXP的文本开始,一直到匹配END-REGEXP的文本结束,这这段文本,都不做拼写检查.

  其中END-REGEXP可以是string,也可以是symbol

+ (START-REGEXP  END-REGEXP)
  
  表示从匹配START-REGEXP的文本开始,一直到匹配END-REGEXP的文本结束,这这段文本,都不做拼写检查.

  其中END-REGEXP只是string

+ (START-REGEXP FUNCTION ARGS)

  类似(START-REGEXP END-REGEXP)

  但这里使用(apply FUNCTION ARGS)返回的值作为END-REGEXP

下面是一段从Endless Parentheses中摘录下来的代码,用于设置ispell作用在org-mode中的配置
#+BEGIN_SRC emacs-lisp
  (defun endless/org-ispell ()
    "Configure `ispell-skip-region-alist' for `org-mode'."
    (make-local-variable 'ispell-skip-region-alist)
    (add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
    (add-to-list 'ispell-skip-region-alist '("~" "~"))
    (add-to-list 'ispell-skip-region-alist '("=" "="))
    (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC")))
  (add-hook 'org-mode-hook #'endless/org-ispell)
#+END_SRC
* ediff
** 使用ediff对比同一文件中的不同文本块
通过命令`M-x ediff-region-wordwise'或`M-x ediff-region-wordwise'可以对比任何文件(包括同一个文件)中的任意两个region的内容.

